### ISSUE TITLE
Broken on dual monitors

### ISSUE THREAD

**Issue by tenten8401** [iabem97/komorebi#6] opened 2017-02-07 02:21 UTC
I've got Dual 1080p monitors running on Arch Linux and it's just broken. It stretches between the monitors, which is really annoying for centered clocks and system stats.

**Comment by yafp** [comment] 2017-02-07 07:19
I can confirm that (running 2 displays with 1920x1200 each)

* wallpaper is stretched
* clock is centered

**Comment by zaphbbrox** [comment] 2017-02-07 10:54
I also ran into this issue. I'm using KOMOREBI on Antergos with 2 displays at 1680x1050.  
Would be nice to change the position of the clock and sysinfos via the menu.

Great work!

**Comment by iabem97** [comment] 2017-02-07 14:55
I just tried it on a dual monitors computer, and I was able to reproduce the issue.
The issue was Komorebi was set to take the size of all available monitors all together.
Check out the latest code, **I fixed the issue**. However, it displays Komorebi on the main monitor **at the moment**.

Try building Komorebi manually for now and let me know if it's working for you!

**Comment by zaphbbrox** [comment] 2017-02-07 16:40
That was quick!  
It's working as you described with the latest build. Regarding the second screen:  
I like it, because this way I'm able to have my personal wallpapers on this screen.

**Comment by iabem97** [comment] 2017-02-08 03:56
Great. Komorebi won't take over other monitors but it will just set the wallpaper to whatever you have on other monitors (aka. Komorebi runs on main monitor but others just have the wallpaper while keeping your personal stuff)

**Comment by iabem97** [comment] 2017-02-08 04:22
A fix has been pushed out. Now Komorebi should change the wallpaper on all of your monitors without affecting your work on other monitors.

**Closed** 2017-02-09 04:01 UTC

**Comment by skullplayzyt** [comment] 2021-04-26 18:52
how do i build komorebi from the source code?
PS: i am new so i don't know much about i
